### ISSUE TITLE
i think i wish the constrcutor was public

### ISSUE THREAD

**Issue by raould** [back2dos/tinkerbell#24]
it is sorta sad to end up manually inserting
  public function new() {}
all the time.

**Comment by back2dos** [comment]
The constructor defaults to public, if the instance takes parameters through `= _`, but will leave it untouched otherwise. The reasoning behind this is that usually, an empty public constructor usually doesn't make sense.

Making this the default behavior is a matter of a few keystrokes, I just doubt it's a good idea. If you really have this a lot, then this smells like an [anemic domain model](http://en.wikipedia.org/wiki/Anemic_domain_model).

**Comment by raould** [comment]
hm, ok, sorry i must be confused, then there's no issue. thanks.

**Comment by back2dos** [comment]
Ok. Well in case you change your mind, let me know ;)
